### ISSUE TITLE
### Checklist

### ISSUE THREAD

**Issue by brubriele** [brubriele/lib-scale-chord-convert#1]
- [x] **Lógica**: testar métodos e funcionalidades em IDE para posterior implementação.

- [x] **index.js**: Funcionalidade essencial implementada em ES¨e Refatorada.

- [x] **Testes:** Test/index.spec.js em  Mocha e NYC. 

- [x] **package.json**: nome, versão, descrição, autores, licença, dependências, scripts (pretest, test, ...)

- [x] **.gitignore**: Ignorar node_modules ou outras pastas que não devem ser incluídas no controle de versões (git).

- [x] **README**: especificações do produto, finalidade, como instalar, regras de uso (conceito semitom/majorScale)

- [x] **Finalização**: publicação npm e up de  arquivos no GitHub.
